"""Build Markdown reports from a fluent API, extensible with custom blocks.

Most callers need only ``MarkdownReport`` and the built-in blocks such as
``Callout``, ``Figure``, ``Table``, and ``TableOfContents``. The rest of this
surface exists for writing custom blocks: implement ``ReportBlock`` (or
``DeferredReportBlock``) and build the ``BlockContent`` you return with the token
builders and ``render_template``.
"""

__version__ = "0.0.1a3"

from .callout import Callout, CalloutKind
from .code_block import CodeBlock
from .dataframe_formatting import format_dataframe, format_dataframe_csv
from .diagram import (
    BORDER_WIDTH,
    CANVAS_GRADIENT,
    CENTERED_NODE_HEIGHT,
    DARK_PALETTE,
    DEFAULT_FONT_FAMILY,
    FIBONACCI_SPACE,
    GOLDEN_RATIO,
    ICON_NODE_HEIGHT,
    INFORMATION_NODE_HEIGHT,
    LANE_HEADER,
    LIGHT_PALETTE,
    PANEL_CAPTION_BAND,
    PANEL_HEADING_BAND,
    TITLE_NODE_HEIGHT,
    TYPE_SCALE,
    Diagram,
    DiagramTheme,
    LucideIcon,
    NodeRole,
    PortSide,
    TextAnchor,
    annotation_callout,
    arrow_key,
    boundary_frame,
    box_label,
    centered_node,
    centered_text_stack,
    color_key,
    decision_node,
    golden_height,
    golden_point,
    golden_split,
    group_panel,
    icon_node,
    information_node,
    junction,
    labeled_connector,
    legend_header,
    list_node,
    lucide_icon_element,
    node_paint,
    node_port,
    repeated_stack,
    svg_element,
    swimlane,
    theme_palette,
    title_node,
)
from .figure import Figure, FigureEmbeddingError
from .heading_anchors import HeadingAnchorStyle, slugify
from .markdown_parser import MarkdownParser
from .markdown_tokens import (
    NestedListItem,
    bold_paragraph_tokens,
    fence_token,
    heading_tokens,
    list_item_tokens,
    list_tokens,
    paragraph_tokens,
    raw_token,
    table_cell_tokens,
    table_tokens,
)
from .report import MarkdownReport
from .report_block import BlockContent, DeferredReportBlock, ReportBlock
from .table import Table
from .table_of_contents import TableOfContents, TableOfContentsEntry
from .template_rendering import render_template, render_template_items

__all__ = [
    "BORDER_WIDTH",
    "CANVAS_GRADIENT",
    "CENTERED_NODE_HEIGHT",
    "DARK_PALETTE",
    "DEFAULT_FONT_FAMILY",
    "FIBONACCI_SPACE",
    "GOLDEN_RATIO",
    "ICON_NODE_HEIGHT",
    "INFORMATION_NODE_HEIGHT",
    "LANE_HEADER",
    "LIGHT_PALETTE",
    "PANEL_CAPTION_BAND",
    "PANEL_HEADING_BAND",
    "TITLE_NODE_HEIGHT",
    "TYPE_SCALE",
    "BlockContent",
    "Callout",
    "CalloutKind",
    "CodeBlock",
    "DeferredReportBlock",
    "Diagram",
    "DiagramTheme",
    "Figure",
    "FigureEmbeddingError",
    "HeadingAnchorStyle",
    "LucideIcon",
    "MarkdownParser",
    "MarkdownReport",
    "NestedListItem",
    "NodeRole",
    "PortSide",
    "ReportBlock",
    "Table",
    "TableOfContents",
    "TableOfContentsEntry",
    "TextAnchor",
    "annotation_callout",
    "arrow_key",
    "bold_paragraph_tokens",
    "boundary_frame",
    "box_label",
    "centered_node",
    "centered_text_stack",
    "color_key",
    "decision_node",
    "fence_token",
    "format_dataframe",
    "format_dataframe_csv",
    "golden_height",
    "golden_point",
    "golden_split",
    "group_panel",
    "heading_tokens",
    "icon_node",
    "information_node",
    "junction",
    "labeled_connector",
    "legend_header",
    "list_item_tokens",
    "list_node",
    "list_tokens",
    "lucide_icon_element",
    "node_paint",
    "node_port",
    "paragraph_tokens",
    "raw_token",
    "render_template",
    "render_template_items",
    "repeated_stack",
    "slugify",
    "svg_element",
    "swimlane",
    "table_cell_tokens",
    "table_tokens",
    "theme_palette",
    "title_node",
]
